language: node_js
node_js:
  - "8"
  - "10"
  - "12"

install:
  - npm ci

before_script:
  - npm run compile

script:
  - npm run compile
  - npm run lint
  - npm test

cache:
  directories:
  - "$HOME/.npm"
